# Generated by Django 3.0.1 on 2020-01-10 10:56

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200110_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to=user.models.Photo.correct_dir),
        ),
    ]
