# Generated by Django 3.0.1 on 2020-01-09 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
