# Generated by Django 3.0.1 on 2020-01-17 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
    ]
