# Generated by Django 3.0.1 on 2020-01-17 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200117_1750'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
